library(MatrixEQTL)
source('meQTL_func.R')
source('CorrBoxPlotZeb.R')
expr<-read.table('liver_expression.out.filter', header = TRUE, stringsAsFactors = FALSE)
genot<-read.table('CNV_matrix.out.filter', header = T, stringsAsFactors=F)
me<-cismeqtl('CNV_matrix.out.filter','CNV_position','liver_expression.out.filter','gene_position','liver_CISresults',0.05)
CorrBoxPlot(me, .2, expr, genot, visual=T, 'liver_plots.pdf')
expr<-read.table('kidney_expression.out.filter', header = TRUE, stringsAsFactors = FALSE)
me<-cismeqtl('CNV_matrix.out.filter','CNV_position','kidney_expression.out.filter','gene_position','kidney_CISresults',0.05)
CorrBoxPlot(me, .2, expr, genot, visual=T, 'kidney_plots.pdf')
#expr<-read.table('kidney_expression.miR_out.filter', header = TRUE, stringsAsFactors = F)
#genot<-read.table('kidney_miRNA_matrix.miR_out',header=T, stringsAsFactors=F)
me<-cismeqtl('kidney_miRNA_matrix.miR_out','kidney_miRNA_pos.snps','kidney_expression.miR_out.filter','gene_position','kidney_miRNA_CISresults',0.05)
#CorrBoxPlot(me, .20, expr, genot, visual=T, 'kidney_miRNA_plots.pdf')
#expr<-read.table('liver_expression.miR_out.filter', header = TRUE, stringsAsFactors = F)
#genot<-read.table('liver_miRNA_matrix.miR_out',header=T, stringsAsFactors=F)
me<-cismeqtl('liver_miRNA_matrix.miR_out','liver_miRNA_pos.snps','liver_expression.miR_out.filter','gene_position','liver_miRNA_CISresults',0.05)
#CorrBoxPlot(me, .20, expr, genot, visual=T, 'liver_miRNA_plots.pdf')
me<-cismeqtl('CNV_matrix.miR_expr_out.filter','CNV_position','kidney_miRNA_expression.miR_expr_out','kidney_miRNA_pos.gene','kidney_miRNA_CNV_CISresults',0.05)
me<-cismeqtl('CNV_matrix.miR_expr_out.filter','CNV_position','liver_miRNA_expression.miR_expr_out','liver_miRNA_pos.gene','liver_miRNA_CNV_CISresults',0.05)
