source('expression_sd_filter.R')
expr<-expression_filter('kidney_expression.out', 0.05)
expr<-expression_filter('liver_expression.out', 0.05)
expr<-expression_filter('liver_expression.miR_out', 0.05)
expr<-expression_filter('kidney_expression.miR_out',0.05)
expr<-expression_filter('liver_miRNA_expression.miR_expr_out',0.05)
expr<-expression_filter('kidney_miRNA_expression.miR_expr_out',0.05)
