source('code/expression_sd_filter.R')
expr<-expression_filter('data/kidney_expression.out', 0.05)
expr<-expression_filter('data/liver_expression.out', 0.05)
expr<-expression_filter('data/liver_expression.miR_out', 0.05)
expr<-expression_filter('data/kidney_expression.miR_out',0.05)
expr<-expression_filter('data/liver_miRNA_expression.miR_expr_out',0.05)
expr<-expression_filter('data/kidney_miRNA_expression.miR_expr_out',0.05)
expr<-expression_filter('data/liver_miRNA_expression.miR_out',0.05)
expr<-expression_filter('data/kidney_miRNA_expression.miR_out',0.05)
